### ISSUE TITLE
Can the same be done for WebP?

### ISSUE THREAD

**Issue by voland62** [davidmz/apng-js#13]
Could webp-js exist?

**Comment by davidmz** [comment]
It is possible to split animated WebP to static WebP frames. The WebP container (not codec!) format is pretty simple, you can see the https://github.com/davidmz/apng2webp/, it builds animated WebP from static frames. But to show these frames on canvas, browser must have WebP support (which implies native animated WebP support too).

**Comment by voland62** [comment]
Wow, cool! 
I'll try this ASAP..

**Comment by myeongwooni** [comment]
@voland62 
Hi, did you try it??
I need to split Webp images ;((
