### ISSUE TITLE
Seek to a certain frame

### ISSUE THREAD

**Issue by RonnyO** [davidmz/apng-js#14]
Awesome project, thanks! 

Some of my animations actually have a "freeze frame" which isn't 0, so something like `seek(46)` would be very helpful.

Right now I may `createImage` for that frame and draw it myself on the context, it's dirty. WDYT?

**Comment by davidmz** [comment]
It is not so simple, the APNG frames are not independent (in general) and to properly render 46-th frame we must also render all 46 (including 0) previous frames.

So the correct way is to .stop() the player and call it's .renderNextFrame() 46 times. Or, if you want just to pause playback on this frame, listen the 'frame' event of player and .pause() it.

**Comment by RonnyO** [comment]
Thank you! did that, awkward but it works 😅
Do you think it makes sense to wrap that in a `seek` method or leave that to developers?

**Comment by davidmz** [comment]
I think it's best left to the developers. This is a potentially costy operation (we have to sequentially render all frames on canvas), and it's better if the developers understands what he's doing.

**Comment by RonnyO** [comment]
Thank you, closing. Keep it up! 🚀
