### ISSUE TITLE
Possible to place the animation somewhere else on canvas?

### ISSUE THREAD

**Issue by anderthalb** [davidmz/apng-js#22]
Hi @davidmz,

really nice work you did with this library! Many thanks so far, it works great.

One question though, is it possible to place the animation somewhere else on the canvas instead of 0:0? I'm not a canvas-expert and it your library doesn't provide something like this, or? 

Many thanks in advance and cheers, Christian

**Comment by davidmz** [comment]
It can be an interesting feature:) No, this library cannot do that, but there is some workaround. You can create a canvas context, [transform](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations) it as you want, and pass it to the APNG player function. The APNG animation will be played transformed (translated/scaled/rotated and so on).

**Comment by anderthalb** [comment]
Thanks for the tip
