### ISSUE TITLE
frame show bug

### ISSUE THREAD

**Issue by wuzhentao** [davidmz/apng-js#26]
like this 
![image](https://user-images.githubusercontent.com/12572949/124556578-04e64980-de6b-11eb-85ea-515c3f0ecf50.png)

**Comment by davidmz** [comment]
Most likely (as far as I can say without seeing the file) it is not a bug. The APNG frame is not a standalone image, but the "patch" to a previously rendered image. So it can look weird being shown in isolation.

**Comment by wuzhentao** [comment]
![d12](https://user-images.githubusercontent.com/12572949/124692803-d4f18180-df10-11eb-8d64-a718fcfb54db.png)
