### ISSUE TITLE
Transparency applied to non-changed pixels? 

### ISSUE THREAD

**Issue by dan-toonkids** [davidmz/apng-js#30]
Hi,
I'm having a weird issue.
When I call my apng with an img tag it looks fine.
When I display it after parsing with the parseAPNG() function it seems like that all the pixels that aren't changing from frame to frame became transparent and discarded (images cropped).
Is there a way to avoid this?
Thanks :)
<img width="721" alt="Screen Shot 2022-01-06 at 4 23 15 PM" src="https://user-images.githubusercontent.com/67740929/148415259-da6fce55-2c39-4875-b0dd-6692e3612473.png">

**Comment by davidmz** [comment]
Generally, the APNG file doesn't keep a full picture for each frame. Only the first frame is included fully, of the others only the changed parts are recorded.

You can examine your file on the https://davidmz.github.io/apng-js/ page

**Comment by dan-toonkids** [comment]
I see, thanks !
How can I solve this using the frame.imageElement? (after calling apng.createImages() ofcourse..)

**Comment by davidmz** [comment]
You can create player and use it renderNextFrame() method to render all frames from 0 to desired number on canvas. If you need an image file, you should call then canvas.toDataURL("image/png") or something.

It is the only way to obtain the full picture of N-th frame.

**Comment by dan-toonkids** [comment]
Great perfect !
This solved my problem :)
Thanks again for writing this library !!
