### ISSUE TITLE
PNG to APNG in NodeJS?

### ISSUE THREAD

**Issue by 1fairyfox** [davidmz/apng-js#34]
I'm using NodeJS and just want to read in a bunch of png files and output them to apng, i'm not interested in anything browser related nor am I interested in reading in an existing apng file. I thought your program could do this but maybe i'm wrong, Is your program just for managing existing apng files?

**Comment by davidmz** [comment]
This library is only for APNG parsing/playing. It cannot create a new APNG from existing frames.
