### ISSUE TITLE
i try to use getPlayer but receive an err Image creation error(in react)

### ISSUE THREAD

**Issue by THERESASEKAIICHIBANKAWAII** [davidmz/apng-js#35]
async createApngPlayer(url, ctx, options = {}) {
    const imgBuffer = await this.getImgBuffer(url);
    const apng = parseAPNG(imgBuffer);
    Object.keys(options).forEach(key => {
      apng[key] = options[key];
    });
    // apng.createImages().then(()=>{
    //   console.log();
    // }).catch((err) => {
    //   console.log(err,'播放err');
    // });
    apng.getPlayer(ctx).then(player1=>{
      console.log(player1, '播放');
      player1.play();
    }).catch(err => {
      console.log(err, '播放');
    });
    // const player = await apng.getPlayer(ctx);
    console.log(player, '播放');
    return player;
  }

i can log apng but this code cannot return player with err 'Image creation error'.

if createImages first ,err in getPlayer will be 'Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D'
and err in createImanges 'Image creation error'.

**Comment by davidmz** [comment]
Perhaps the problem is in mixing async/await and .then approach. It would be correct to do it this way:
```js
async createApngPlayer(url, ctx, options = {}) {
  const imgBuffer = await this.getImgBuffer(url);
  const apng = parseAPNG(imgBuffer);
  Object.keys(options).forEach(key => { apng[key] = options[key]; });

  await apng.createImages();
  const player = await apng.getPlayer(ctx);
  player.play();
  return player;
}
```
