### ISSUE TITLE
How can I control the size of parsed Image?

### ISSUE THREAD

**Issue by sainyanhtay** [davidmz/apng-js#6]
Now, canvas can only show the original size of APNG. I want to control dynamically the size of the animated image in html or js. How should i do ?

**Comment by davidmz** [comment]
You can use a regular CSS width/height to contol size of canvas element.

**Comment by sainyanhtay** [comment]
Yes. It can't show the image when reducing the canvas element. Because the image which parsed APNG image size from canvas still remains the original size.

**Comment by sainyanhtay** [comment]
I think It needs to control since `parseAPNG(buffer)` method was called. But, I don't know how to control the size of the parsed image dynamically for each image in your method. How can I do for that, @davidmz . Thanks

**Comment by davidmz** [comment]
I'm afraid I don't understand your problem. This library does not create canvas elements. You can create canvas yourself, assign it the right size via CSS, and start playing APNG in it.

It may be easier if you show the problem code on codesandbox, for example.

**Comment by sainyanhtay** [comment]
I was testing in your demo project.

-I have the image(APNG) to upload , width : 1920px, height: 1080px
-But for example : I want to show that image only width 300px , height 300px
-So I change css style of  `apng-ani` div and canvas element , then the image can't show.

**Comment by davidmz** [comment]
I just opened the demo page, added a `canvas { width: 300px; }` style via Chrome inspector and loaded APNG file. The file was animated normally and the width of the element on the page was 300px. So it works the way it should.
![image](https://user-images.githubusercontent.com/132120/69499052-4c6eca80-0eff-11ea-9c0b-6f355722e06f.png)

**Comment by sainyanhtay** [comment]
![Annotation 2019-11-25 012441](https://user-images.githubusercontent.com/29755444/69499630-708fd300-0f22-11ea-9f43-449450067f9f.jpg)


I changed only width 300px from the original 480px. Then, It does not show the entire image. You can check the image by [https://apng.onevcat.com/assets/elephant.png](url)

**Comment by davidmz** [comment]
Please send a link to a live demonstration of the problem.

**Comment by championboylay** [comment]
Hi davidmz, could you see https://estates-officer-elephant-63118.netlify.com/ for resizing issue. I made 
 canvas.width = 300;
 canvas.height = 400;

**Comment by davidmz** [comment]
Ok, you should _not_ set the width/height of canvas other than width/height of image. Frames renders in 1:1 scale so it's natural that if you change that, the picture will be cropped. But the width/height attributes don't determine rigidly the physical dimensions of element. You can set any size for canvas by CSS, regardless of the width and height attributes values.

**Comment by championboylay** [comment]
OMG! It work like a charm 👍

**Comment by sainyanhtay** [comment]
Thanks @davidmz  . It works for me.
