### ISSUE TITLE
Add type for this project.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [davidmz/apng-js#8]
I want to help provide type support for this repo. May I write a `.d.ts` for this or help to change the whole project from JavaScript to TypeScript?

**Comment by davidmz** [comment]
Yes, of course, I'd be happy to have your help.

**Comment by xiaoxiangmoe** [comment]
OK，I'll creating a pull request to change this from js to ts for better IDE intellisense.

**Comment by xiaoxiangmoe** [comment]
@davidmz Done. I would be very happy if you could review it, thank you.

**Comment by xiaoxiangmoe** [comment]
@davidmz  Hi, is it better to add types in `@types/apng-js` or in the repo itself?

**Comment by davidmz** [comment]
Hi, sorry for such late response. Your code is fine, I merged it. Thank you!
